agendamento/urls.py
from django.urls import path
from .views import index, agenda_selecionar, agenda_ver, agenda_horarios_futuros
from .views import solicitacao_cancelar, solicitacao_visualizar


app_name = 'agendamento'

urlpatterns = [
    path('', index, name='index'),
    path('agendas/', agenda_selecionar, name='agenda_selecionar'),
    path('agendas/<int:id>/', agenda_ver, name='agenda_ver'),
    path('agendas/<int:id>/<data>/', agenda_horarios_futuros, name='agenda_horarios_futuros'),
    path('solicitacao/<int:id>/cancelar/', solicitacao_cancelar, name='solicitacao_cancelar'),
    path('solicitacao/<int:id>/', solicitacao_visualizar, name='solicitacao_visualizar'),
]

urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from rest_framework import urls, schemas


admin.site.site_url = settings.ADMIN_SITE_URL
admin.site.index_title = settings.ADMIN_SITE_TITLE
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('sead/', RedirectView.as_view(url=settings.URL_PATH_PREFIX)),
    path(settings.URL_PATH_PREFIX[1:],include('suapintegration.urls')),
    path(
        settings.URL_PATH_PREFIX[1:],
        include(
            [
                path('admin/', admin.site.urls),
                path('markdownx/', include('markdownx.urls')),
                # path('', RedirectView.as_view(pattern_name='admin:index')),
                path('', include('agendamento.urls')),
            ]
        )
    ),
    path('', RedirectView.as_view(url=settings.URL_PATH_PREFIX)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path(settings.URL_PATH_PREFIX + '__debug__/', include(debug_toolbar.urls))]

agendamento/models.py
import calendar
from datetime import datetime, date, time, timedelta
from django.core.mail import send_mail
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
from django.utils.timezone import now, localtime, make_aware
from django.db.models import Model, TextChoices
from django.db.models import DateField, BooleanField, NullBooleanField, DateTimeField, TextField, TimeField, PositiveIntegerField
from django.db.models import ImageField, ManyToManyField, URLField
from django.dispatch import receiver
from django.contrib.auth.models import Group
from django.db.models import Model, CharField, EmailField, BooleanField, DateTimeField, ForeignKey, CASCADE
from django.db.models import ForeignKey, CASCADE
from suap_ead.fields import StringField, NullStringField, nullable, nullable_phone, FK, NullFK
from django.contrib.auth import get_user_model
from threading import current_thread
from sc4py.datetime import today, daterange
from datetimerange import DateTimeRange
from django.forms.models import model_to_dict


class TipoVinculo(Model):
    descricao = StringField('Descrição')

    class Meta:
        verbose_name = _("Vínculo")
        verbose_name_plural = _("Vínculos")
        ordering = ['descricao']

    def __str__(self):
        return f'{self.descricao}'


class Campus(Model):
    suap_id = StringField('ID no SUAP', unique=True)
    sigla = StringField('Sigla', unique=True)
    descricao = StringField('Descrição')
    url = URLField('URL', max_length=255, **nullable)
    active = BooleanField('Ativo')

    class Meta:
        verbose_name = "Campus"
        verbose_name_plural = "Campi"
        ordering = ['sigla']

    def __str__(self):
        return f'{self.sigla}'


class Diretoria(Model):
    campus = FK(_('Campus'), Campus)
    sigla = StringField('Sigla')
    descricao = StringField(_('Descrição'))
    active = BooleanField('Ativo')

    class Meta:
        verbose_name = "Diretoria"
        verbose_name_plural = "Diretorias"
        ordering = ['sigla']
        unique_together = [['campus', 'sigla'], ]

    def __str__(self):
        return f'{self.sigla}/{self.campus.sigla}'


class Curso(Model):
    diretoria = FK(_('Diretoria'), Diretoria)
    codigo = StringField('Código', unique=True)
    nome = StringField('Nome')
    descricao = StringField('Descrição')
    active = BooleanField('Ativo')

    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"
        ordering = ['nome']

    def __str__(self):
        return f'{self.codigo} - {self.nome}'


class Turma(Model):
    curso = FK(_('Curso'), Curso)
    codigo = StringField('Código', unique=True)
    active = BooleanField('Ativo')

    class Meta:
        verbose_name = "Turma"
        verbose_name_plural = "Turmas"
        ordering = ['codigo']

    def __str__(self):
        return f'{self.codigo}'

    def save(self, *args, **kwargs):
        parts = self.codigo.split(".")
        if len(parts) != 4:
            raise ValidationError(
                "O código do curso está errado, deve ser:"
                " 'AAAAO.P.CCCCCC.TT'. AAAA=Ano, O=Perído de oferta,"
                " P=Periodo do curso, CCCCCC=Código do curso, TT=Turma")
        codigo_curso = parts[2]
        if codigo_curso != self.curso.codigo:
            raise ValidationError(
                f"O código do curso está errado é {self.curso.codigo},"
                f" mas você informou no código da turma é que o código curos é {codigo_curso}.")

        super().save(*args, **kwargs)


class Criterio(Model):
    titulo = StringField(_("Título"))

    class Meta:
        verbose_name = _("Critério")
        verbose_name_plural = _("Critérios")
        ordering = ['titulo']

    def __str__(self):
        return f'{self.titulo}'


class Agenda(Model):
    nome = StringField(_('Nome da agenda'))
    janela = PositiveIntegerField(_("Janela de atendimento (min)"), help_text=_("Alterar a janela depois de já ter solicitações não muda a tempo da reserva da solicitação"))
    inicio = DateField(_('Início'), help_text=_("Esta agenda começa que dia? Alterar a data de início da agenda não altera as solicitações"))
    fim = DateField(_('Fim'), help_text=_("Esta agenda termina que dia. Alterar a data de fim da agenda não altera as solicitações"))
    informacao = TextField(_('Informações aos solicitantes'), **nullable)
    restrito_aos_campi = ManyToManyField(Campus, verbose_name='Restrito aos campi', blank=True)
    restrito_aas_diretorias = ManyToManyField(Diretoria, verbose_name='Restrito às diretorias', blank=True)
    restrito_aos_cursos = ManyToManyField(Curso, verbose_name='Restrito aos cursos', blank=True)
    restrito_aas_turmas = ManyToManyField(Turma, verbose_name='Restrito às turmas', blank=True)
    restrito_aos_vinculos = ManyToManyField(TipoVinculo, verbose_name='Restrito às vínculos', blank=True)

    class Meta:
        verbose_name = _("Agenda")
        verbose_name_plural = _("Agendas")
        ordering = ['inicio']

    def __str__(self):
        return f"{self.nome}"

    @classmethod
    def agendas_abertas(cls):
        return Agenda.objects.filter(fim__gte=date.today())

    def solicitacoes_futuras(self, user=None):
        return Solicitacao.objects.filter(inicio__gte=now())

    @property
    def vagas_futuras(self):
        result = []

        vagas = {}
        for x in self.vaga_set.all():
            if int(x.dia) not in vagas:
                vagas[int(x.dia)] = []
            vagas[int(x.dia)].append(x)

        dias = set([int(x.dia) for x in self.vaga_set.all()])

        for data in daterange(max(self.inicio, today()), self.fim):
            if data.weekday() in dias:
                for vaga in vagas[d.weekday()]:
                    result.append({ "dia": d, "vaga": vaga })
        return result

    @property
    def condicao(self):
        hoje = date.today()
        if hoje >= self.inicio and hoje <= self.fim:
            return _("Em andamento")
        if self.fim > hoje:
            return _("Encerrado")
        return _("Planejado")
    condicao.fget.short_description = _("Condição")
    

    def solicitacao_futura(self, solicitante):
        return Solicitacao.objects.filter(
            agenda=self, inicio__gte=now(), status__in=Solicitacao.bloqueantes, solicitante=solicitante
        ).order_by('inicio').first()

    @property
    def datas_futuras(self):
        dias = set([int(x.dia) for x in self.vaga_set.all()])
        return [data for data in daterange(max(self.inicio, today()), self.fim) if data.weekday() in dias]

    def horarios_futuros(self, data, solicitante):
        quando = self.solicitacao_futura(solicitante)
        if quando is not None:
            inicio = localtime(quando.inicio).strftime('%d/%m/%Y às %H:%M')
            raise Exception(f"Você já tem uma solicitação prevista para {inicio} na situação {quando.status}")
            
        if not (max(self.inicio, date.today()) <= data.date() <= self.fim):
            raise Exception(f"A data deve ser entre {self.inicio} e {self.fim}, mas você informou a data {data}.")

        result = []
        for vaga in self.vaga_set.filter(dia=data.weekday()):
            time_range = DateTimeRange(datetime.combine(data, vaga.inicio), datetime.combine(data, vaga.fim))
            for dt in time_range.range(timedelta(minutes=self.janela)):
                if make_aware(dt) > now():
                    quantidade = Solicitacao.objects.filter(
                        agenda=self, 
                        inicio=dt, 
                        status__in=[Solicitacao.Status.DEFERIDO, Solicitacao.Status.SOLICITADO]
                    ).count()
                    if quantidade < vaga.atendimentos:
                        result.append(dt)
        return result[:-1]


class Vaga(Model):
    class DiaDaSemana(TextChoices):
        SEGUNDA = str(calendar.MONDAY), _('Seg')
        TERCA = str(calendar.TUESDAY), _('Ter')
        QUARTA = str(calendar.WEDNESDAY), _('Qua')
        QUINTA = str(calendar.THURSDAY), _('Qui')
        SEXTA = str(calendar.FRIDAY), _('Sex')
        SAB = str(calendar.SATURDAY), _('Sab')
        DOM = str(calendar.SUNDAY), _('Dom')
    agenda = FK(_('Agenda'), Agenda)
    dia = StringField(_('Dia da semana'), choices=DiaDaSemana.choices)
    inicio = TimeField(_('Início'))
    fim = TimeField(_('Fim'))
    atendimentos = PositiveIntegerField(_('Quantidade de atendimentos na janela'))

    class Meta:
        verbose_name = _("Vaga")
        verbose_name_plural = _("Vagas")
        ordering = ['dia', 'inicio']

    def __str__(self):
        return f"Até {self.atendimentos} atendimentos no dia {self.dia}, das {self.inicio} às {self.fim}"


class Autorizacao(Model):
    agenda = FK(_('Agenda'), Agenda)
    grupo = FK(_('Papel'), Group)
    user = FK(_('Usuário'), get_user_model())
    active = BooleanField('Ativo')

    class Meta:
        verbose_name = _("Autorização")
        verbose_name_plural = _("Autorizações")
        ordering = ['active', 'grupo', 'user']
        unique_together = [['agenda', 'user']]

    def __str__(self):
        return f"O usuário {self.user} na agenda {self.agenda} tem o papel {self.grupo}"


class AgendaCriterio(Model):
    agenda = FK(_("Agenda"), Agenda)
    criterio = FK(_("Critério"), Criterio)
    active = BooleanField(_("Ativo"))


    class Meta:
        verbose_name = _("Critério da agenda")
        verbose_name_plural = _("Critérios das agendas")
        ordering = ['criterio__titulo']
        unique_together = [['agenda', 'criterio']]

    def __str__(self):
        return f'{self.criterio}'


class Solicitacao(Model):
    class Status(TextChoices):
        SOLICITADO = 'Solicitado', _('Solicitado')
        DEFERIDO = 'Deferido', _('Deferido')
        INDEFERIDO = 'Indeferido', _('Indeferido')
        CANCELADO = 'Cancelado', _('Cancelado')

    bloqueantes = [Status.SOLICITADO, Status.DEFERIDO]

    agenda = FK(_('Agenda'), Agenda)

agendamento/forms.py
import re
from django.conf import settings
from django.shortcuts import resolve_url
from django import forms
from django.forms import Form, ModelForm, DateTimeInput
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.http.request import HttpRequest
from .models import Solicitacao


# class SolicitacaoForm(forms.Form):
#     inicio = DateTimeField(
#         input_formats=['%d/%m/%Y %H:%M'],
#         widget=DateTimeInput(attrs={
#             'class': 'form-control datetimepicker-input',
#             'data-target': '#datetimepicker1'
#         })
#     )

class SolicitacaoForm(ModelForm):

    def __init__(self, agenda, solicitante, *args, **kwargs):
        self.agenda = agenda
        self.solicitante = solicitante
        super().__init__(*args, **kwargs)

    class Meta:
        model = Solicitacao
        fields = ['inicio', 'observacao']
        widgets = {
            'inicio': DateTimeInput(),
        }

agendamento/views.py
import json
from datetime import datetime, timedelta
from django.utils.timezone import now
from django.conf import settings
from django.utils.translation import gettext as _
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .models import Agenda, Solicitacao
from .forms import SolicitacaoForm


@login_required
def index(request):
    agendas = Agenda.objects.all()
    solicitacoes = Solicitacao.objects.filter(solicitante=request.user)
    return render(
        request, 
        'agendamento/index.html', 
        context={
            'agendas': agendas,
            'solicitacoes': solicitacoes,
            'title': _('Início'),
            'site_url': settings.ADMIN_SITE_URL,
            'site_header': settings.ADMIN_SITE_HEADER,
            'index_title': settings.ADMIN_SITE_TITLE,
        }
    )


@login_required
def agenda_selecionar(request):
    agendas = Agenda.agendas_abertas()
    return render(
        request, 
        'agendamento/agenda_selecionar.html', 
        context={
            'agendas': agendas,
            'title': _('Selecione uma agenda'),
            'site_url': settings.ADMIN_SITE_URL,
            'site_header': settings.ADMIN_SITE_HEADER,
            'index_title': settings.ADMIN_SITE_TITLE,
        }
    )


@login_required
def solicitacao_cancelar(request, id):
    solicitacao = get_object_or_404(Solicitacao, id=id, solicitante=request.user)
    solicitacao.status = solicitacao.Status.CANCELADO
    solicitacao.cancelado_em = now()
    solicitacao.save(update_fields={"status", "cancelado_em"})
    return redirect("agendamento:index")


@login_required
def solicitacao_visualizar(request, id):
    solicitacao = get_object_or_404(Solicitacao, id=id, solicitante=request.user)
    return render(request, 'agendamento/solicitacao_visualizar.html', context=locals())


@login_required
def agenda_ver(request, id):
    agenda = get_object_or_404(Agenda, id=id)

    if request.method == 'POST':
        form = SolicitacaoForm(agenda, request.user, request.POST)
        inicio = datetime.fromisoformat(form.data['inicio'])
        Solicitacao.objects.create(
            agenda=agenda,
            solicitante=request.user,
            inicio=inicio,
            fim=inicio + timedelta(minutes=agenda.janela),
            observacao=form.data['observacao']
        )
        return redirect("agendamento:index")
    else:
        form = SolicitacaoForm(agenda, request.user)
    return render(
        request, 
        'agendamento/agenda_ver.html', 
        context={
            'agenda': agenda,
            'form': form,
            'title': _('Escolha um dia/horário para agendar'),
            'site_url': settings.ADMIN_SITE_URL,
            'site_header': settings.ADMIN_SITE_HEADER,
            'index_title': settings.ADMIN_SITE_TITLE,
        }
    )


@login_required
def agenda_horarios_futuros(request, id, data):
    try:
        agenda = get_object_or_404(Agenda, id=id)
        return JsonResponse(agenda.horarios_futuros(datetime.strptime(data, '%Y-%m-%d'), request.user), safe=False)
    except Exception as err:
        return JsonResponse({"error_message": str(err)}, status=412)

agendamento/templates/agendamento/agenda_selecionar.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'agendamento:index' %}">Início</a>
        › <a href="{% url 'agendamento:agenda_selecionar' %}">Agendas</a>
    </div>
{% endblock %}

{% block content %}
<style>
.btn {
    background: #417690;
    color: #fff !important;
    padding: 4px 12px;
    border-radius: 50px;
}
</style>
    {% if agendas.exists %}
        <table class="table" width="100%">
            <thead>
                <tr>
                    <th>Agenda</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                {% for agenda in agendas %}
                <tr>
                    <td>{{agenda.nome}}</td>
                    <td style="text-align: right;">
                        {{solicitacao_futura}}
                        {% if solicitacao_futura %}
                        Agendado para {{solicitacao_futura.inicio}}, duração de {{agenda.janela}} minutos.
                        {% else %}
                        <a class="btn" href="{% url 'agendamento:agenda_ver' agenda.id %}">Agendar</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Não existe agenda aberta no momento.</p>
    {% endif %}
{% endblock content %}

agendamento/templates/agendamento/agenda_ver.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block extrahead %}
<style>
    #id_inicio_time_container, #id_inicio_time_container_error {
        display: none;
    }
    #id_inicio_time_container_selecione {
        background-color: #17a2b8;
        padding: 1rem;
        color: #fff;
    }
    #id_inicio_time_container_error {
        background-color: #f9c7c7;
        padding: 1rem;
        text-align: center;
        color: #111;
    }
    .infor {
        color: #fff !important;
        padding: 1rem !important;
        margin-bottom: .5rem !important;
        background-color: #17a2b8 !important;
        border-radius: 15px;
    }
    .infor dt {
        font-weight: bold;
        margin-top: 0;
        margin-bottom: 1rem;
        font-size: 120%;
    }
    .help_text {
        color: gray;
        font-size: 90%;
    }
</style>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
    function toggle_inicio_time_container() {
        var data = $("#id_inicio_date").val();
        $("#id_inicio_time_container").hide();
        $("#id_inicio_time_container_selecione").hide();
        $("#id_inicio_time_container_error").text('').hide();
        if (data=='') {
            $("#id_inicio_time_container_error").text('').hide();
            $("#id_inicio_time_container_selecione").show();
        } else {
            $.get(data)
                .done(function (data){
                    if ( data && data.length>0 ) {
                        $("#id_inicio_time").empty();
                        for (var i = 0; i < data.length; i++) {
                            var d = new Date(data[i]);
                            $("#id_inicio_time").append($("<option value='" + data[i] + "'>" + ("" + d.getHours()).padStart(2, '0') + ':' + ("" + d.getMinutes()).padStart(2, '0') + "</option>"))
                        };
                        $("#id_inicio_time_container").show();
                    } else {
                        $("#id_inicio_time_container_error").text("Não existe mais possibilidade de reservas para este dia.").show();
                    };
                }).fail(function(jqXHR) {
                    $("#id_inicio_time_container_error").text(jqXHR.responseJSON.error_message).show();
                });
        };
    };
    $(function(){
        $("#id_inicio_date").change(toggle_inicio_time_container);
        toggle_inicio_time_container();
    });
</script>
{% endblock extrahead %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'agendamento:index' %}">Início</a>
        › <a href="{% url 'agendamento:agenda_selecionar' %}">Agendas</a>
        › <a href="{% url 'agendamento:agenda_ver' agenda.id %}">{{title}}</a>
    </div>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Agenda: {{agenda}}</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div style="margin-top: 15px;">
            Eu <b>{{request.user.display_name}} ({{request.user.username}})</b>, usando o email <u>{{request.user.email}}</u>, solicito agendamento<br>
            <label for="id_inicio_date">Em: </label>
            <select name="inicio_date" required="" id="id_inicio_date">
                <option value="">Selecione um período</option>
                {% for vaga in agenda.datas_futuras %}
                <option value="{{vaga|date:'Y-m-d'}}">{{vaga}}</option>
                {% endfor %}
            </select>
            <div id="id_inicio_time_container_selecione">
                Para informar o horário, primeiro selecione o período (dia e turno) acima.
            </div>
            <div id="id_inicio_time_container_error"></div>
            <div id="id_inicio_time_container">
                <label for="id_inicio_time">De: </label>
                <select name="inicio" required="" id="id_inicio_time">
                    <option>08:00 às 08:14</option>
                </select>
            </div>
            <div class="help_text">Com duração de no máximo {{agenda.janela}} minutos.</div>
        </div>
        
        <div style="margin-top: 15px;">
            <dl>
                <dt>Deixe aqui seus comentários para a equipe de avaliação<dt>
                <dd><textarea name="observacao" cols="50" rows="5"></textarea></dd>
                <div class="help_text">Use este campo para informar a equipe responsável pela agenda tudo que o que você desejar.</div>
            </dl class="infor">
            {% if agenda.informacao %}
                <dl class="infor">
                    <dt>Informações desta agenda</dt>
                    <dd>{{agenda.informacao|linebreaks}}</dd>
                </dl>                        
            {% endif %}
        </div>
        <div class="form-group">
                <input type="submit" class="btnSubmit" value="Solicitar">
            </div>
        </div>
    </form>

{% endblock content %}

agendamento/templates/agendamento/base.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block title %}Solicitação de agendamento{% endblock %}

{% block extrahead %}
<style>
    .status {margin-top: 1em;padding: 5px;}
    .status.Solicitado {background: #f9f9c7;}
    .status.Deferido {background: #d2f9c7;}
    .status.Indeferido {background: #f9c7c7;}
    .status.Cancelado {background: #ffe3c5;}
    .btn {
        background: #417690;
        color: #fff !important;
        padding: 4px 12px;
        border-radius: 15px;
    }
    .cancelar {
        background-color: brown;
    }
    .infor {
        margin: 3em;
        color: #fff !important;
        padding: 1rem !important;
        margin-bottom: .5rem !important;
        background-color: #17a2b8 !important;
        border-radius: 15px;
        text-align: center;
    }
</style>
{% endblock extrahead %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'agendamento:index' %}">{{title}}</a>
        {% if user.is_staff %}
        › <a href="{% url 'admin:index' %}">Admin</a>
        › <a href="{% url 'admin:app_list' 'agendamento' %}">Agendamento</a>
        › <a href="{% url 'admin:agendamento_solicitacao_changelist' %}">Solicitações</a>
        {% endif %}
    </div>
{% endblock %}

agendamento/templates/agendamento/index.html
{% extends "agendamento/base.html" %}
{% load i18n %}

{% block content %}
    <p>Olá, você acessou como <b>{{user.name}} ({{user.username}})</b>, cujo email é o <b>{{user.email}}</b>.</p>

    <h2>Suas solicitações de agendamento</h2>
    {% if solicitacoes.exists %}
        <ol style="list-style: none; padding: 0;">
        {% for solicitacao in solicitacoes %}
            <li class="status {{solicitacao.status}}" style="padding: 10px;">
                <div><b>Agenda: {{ solicitacao.agenda }}</b></div>
                <div>Data: <b>{{solicitacao.inicio}}</b></div>
                <div>Situação: <b>{{solicitacao.status}}</b></div>
                <div><br><a class="btn" href="{%url 'agendamento:solicitacao_visualizar' solicitacao.id%}">Ver detalhes</a></div>
            </li>
        {% endfor %}
        </ol>
    {% else %}
        <ul>
            <li>Você não tem solicitações de agendamento.</li>            
        </ul>
    {% endif %}
    <br>
    <p><a class="btn" href="{% url 'agendamento:agenda_selecionar' %}">Nova solicitação de agendamento</a></p>
    <p class="infor">Você deve voltar a esta página sempre que você quiser verificar o andamento da solicitação ou fazer novas solicitações.</p>
{% endblock content %} 

agendamento/templates/agendamento/solicitacao_visualizar.html
{% extends "agendamento/base.html" %}
{% load i18n %}

{% block content %}
    <p>Olá, você acessou como <b>{{user.name}} ({{user.username}})</b>, cujo email é o <b>{{user.email}}</b>.</p>

    <h2><span class="status {{solicitacao.status}}" style="font-size: 80%;">{{solicitacao.status}}</span> Agenda: {{ solicitacao.agenda }}</h2>
    
    <dl style="padding: 10px;">
        <dt>Agendado para</dt><dd>{{solicitacao.inicio}}</dd>
        <dt>Suas observações</dt><dd>{{solicitacao.observacao|linebreaks}}</dd>
        <dt>Situação</dt>
        <dd><span class="status {{solicitacao.status}}">{{solicitacao.status}}:
            {% if solicitacao.status == solicitacao.Status.SOLICITADO %}
                Ainda <b>aguarda confirmação</b>, ou seja, ainda não adianta comparecer ao local marcado.
            {% endif%}
            {% if solicitacao.status == solicitacao.Status.DEFERIDO %}
                Comparecer em 15min antes na sede do Campus. O atendimento deverá durar até {{solicitacao.agenda.janela}} minutos.
            {% endif%}
            {% if solicitacao.status == solicitacao.Status.INDEFERIDO %}
                <b>Não adianta comparecer</b> ao local marcado nesta data.
            {% endif %}
            {% if solicitacao.status == solicitacao.Status.CANCELADO %}
                Seu agendamento para <i>{{solicitacao.inicio}}</i> <b>foi CANCELADO</b>, ou seja, não compareça ao local marcado nesta data.
            {% endif%}</span>
        </dd>
        {% if solicitacao.status == solicitacao.Status.INDEFERIDO %}
            <dt>Motivo</dt><dd>{{solicitacao.justificativa}}</dd>
            {% if solicitacao.criterioavaliado_set %}
                <dt>Critérios avaliados</dt>
                <ol>
                    {% for criterio in solicitacao.criterioavaliado_set.all %}
                        <li>{{criterio}}: {% if criterio.confere %}Sim{%else%}Não{%endif%}</li>
                    {% endfor  %}
                </ol>
            {% endif %}
        {% endif %}
        <dt>Data</dt><dd>{{solicitacao.inicio}}</dd>
        {% if solicitacao.status == solicitacao.Status.SOLICITADO or solicitacao.status == solicitacao.Status.DEFERIDO %}
            <br><div><a href="{% url 'agendamento:solicitacao_cancelar' solicitacao.id %}" class="btn cancelar">Cancelar esta solicitação</a></div>
        {% endif%}
        
    </dl>
    <div style="color: #fff !important; padding: 1rem !important; background: #17a2b8 !important; border-radius: 5px;">
        <h2>Informações relevantes desta agenda:</h2>
        {{solicitacao.agenda.informacao|linebreaks}}
    </div>
{% endblock content %} 